# Generated by Django 5.0.4 on 2024-04-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_diarista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nome_empresa', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=14)),
                ('estado', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.TextField(max_length=4)),
            ],
        ),
    ]
