# Generated by Django 5.0.4 on 2024-04-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_diarista', '0003_empresa_bairro_empresa_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarista',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='diarista',
            name='rg',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=18),
        ),
    ]
