# Generated by Django 5.0.4 on 2024-04-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_diarista', '0004_alter_diarista_cpf_alter_diarista_rg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cep',
            field=models.CharField(default='', max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diarista',
            name='pix',
            field=models.TextField(max_length=100),
        ),
    ]
